// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/telemetry-platform/alert-service/internal/core/domain"
)

// AlertBroadcaster is an autogenerated mock type for the AlertBroadcaster type
type AlertBroadcaster struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: ctx, alert
func (_m *AlertBroadcaster) Broadcast(ctx context.Context, alert domain.Alert) error {
	ret := _m.Called(ctx, alert)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Alert) error); ok {
		r0 = rf(ctx, alert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with no fields
func (_m *AlertBroadcaster) Subscribe() <-chan domain.Alert {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan domain.Alert
	if rf, ok := ret.Get(0).(func() <-chan domain.Alert); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.Alert)
		}
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: ch
func (_m *AlertBroadcaster) Unsubscribe(ch <-chan domain.Alert) {
	_m.Called(ch)
}

// NewAlertBroadcaster creates a new instance of AlertBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertBroadcaster {
	mock := &AlertBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
