// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/telemetry-platform/alert-service/internal/core/domain"
)

// PositionBroadcaster is an autogenerated mock type for the PositionBroadcaster type
type PositionBroadcaster struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: ctx, pos
func (_m *PositionBroadcaster) Broadcast(ctx context.Context, pos domain.Position) error {
	ret := _m.Called(ctx, pos)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Position) error); ok {
		r0 = rf(ctx, pos)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with no fields
func (_m *PositionBroadcaster) Subscribe() <-chan domain.Position {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan domain.Position
	if rf, ok := ret.Get(0).(func() <-chan domain.Position); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.Position)
		}
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: ch
func (_m *PositionBroadcaster) Unsubscribe(ch <-chan domain.Position) {
	_m.Called(ch)
}

// NewPositionBroadcaster creates a new instance of PositionBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionBroadcaster {
	mock := &PositionBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
