// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/telemetry-platform/alert-service/internal/core/domain"
)

// PositionTracker is an autogenerated mock type for the PositionTracker type
type PositionTracker struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, vehicleID
func (_m *PositionTracker) Get(ctx context.Context, vehicleID int64) (domain.VehicleTrack, error) {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.VehicleTrack
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.VehicleTrack, error)); ok {
		return rf(ctx, vehicleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.VehicleTrack); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		r0 = ret.Get(0).(domain.VehicleTrack)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, vehicleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, track
func (_m *PositionTracker) Set(ctx context.Context, track domain.VehicleTrack) error {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.VehicleTrack) error); ok {
		r0 = rf(ctx, track)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, vehicleID
func (_m *PositionTracker) Delete(ctx context.Context, vehicleID int64) error {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPositionTracker creates a new instance of PositionTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionTracker {
	mock := &PositionTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
