// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/telemetry-platform/geo-service/internal/core/domain"
)

// PositionPublisher is an autogenerated mock type for the PositionPublisher type
type PositionPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, pos
func (_m *PositionPublisher) Publish(ctx context.Context, pos domain.Position) error {
	ret := _m.Called(ctx, pos)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Position) error); ok {
		r0 = rf(ctx, pos)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPositionPublisher creates a new instance of PositionPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionPublisher {
	mock := &PositionPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
