// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VehicleClient is an autogenerated mock type for the VehicleClient type
type VehicleClient struct {
	mock.Mock
}

// ValidateVehicle provides a mock function with given fields: ctx, vehicleID
func (_m *VehicleClient) ValidateVehicle(ctx context.Context, vehicleID int64) error {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateVehicle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVehicleClient creates a new instance of VehicleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehicleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehicleClient {
	mock := &VehicleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
