// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// EventPublisher is an autogenerated mock type for the EventPublisher type
type EventPublisher struct {
	mock.Mock
}

// PublishVehicleDeleted provides a mock function with given fields: ctx, vehicleID, deletedAt
func (_m *EventPublisher) PublishVehicleDeleted(ctx context.Context, vehicleID int64, deletedAt time.Time) error {
	ret := _m.Called(ctx, vehicleID, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for PublishVehicleDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) error); ok {
		r0 = rf(ctx, vehicleID, deletedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventPublisher creates a new instance of EventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mock's expectations.
func NewEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisher {
	mock := &EventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
