// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/telemetry-platform/vehicle-service/internal/core/domain"
)

// VehicleRepository is an autogenerated mock type for the VehicleRepository type
type VehicleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, v
func (_m *VehicleRepository) Create(ctx context.Context, v *domain.Vehicle) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Vehicle) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByPlate provides a mock function with given fields: ctx, plate
func (_m *VehicleRepository) FindByPlate(ctx context.Context, plate string) (*domain.Vehicle, error) {
	ret := _m.Called(ctx, plate)

	if len(ret) == 0 {
		panic("no return value specified for FindByPlate")
	}

	var r0 *domain.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Vehicle, error)); ok {
		return rf(ctx, plate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Vehicle); ok {
		r0 = rf(ctx, plate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, plate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VehicleRepository) GetByID(ctx context.Context, id int64) (*domain.Vehicle, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Vehicle, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Vehicle); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *VehicleRepository) List(ctx context.Context, limit int, offset int) ([]domain.Vehicle, int64, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Vehicle
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Vehicle, int64, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.Vehicle); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *VehicleRepository) SoftDelete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVehicleRepository creates a new instance of VehicleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehicleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehicleRepository {
	mock := &VehicleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
