// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/telemetry-platform/geo-service/internal/core/domain"
)

// PositionService is an autogenerated mock type for the PositionService type
type PositionService struct {
	mock.Mock
}

// Ingest provides a mock function with given fields: ctx, pos
func (_m *PositionService) Ingest(ctx context.Context, pos domain.Position) error {
	ret := _m.Called(ctx, pos)

	if len(ret) == 0 {
		panic("no return value specified for Ingest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Position) error); ok {
		r0 = rf(ctx, pos)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPositionService creates a new instance of PositionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionService {
	mock := &PositionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
