// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/telemetry-platform/geo-service/internal/core/domain"
)

// PositionRepository is an autogenerated mock type for the PositionRepository type
type PositionRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, pos
func (_m *PositionRepository) Save(ctx context.Context, pos domain.Position) error {
	ret := _m.Called(ctx, pos)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Position) error); ok {
		r0 = rf(ctx, pos)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByVehicleID provides a mock function with given fields: ctx, vehicleID
func (_m *PositionRepository) DeleteByVehicleID(ctx context.Context, vehicleID int64) error {
	ret := _m.Called(ctx, vehicleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByVehicleID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, vehicleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPositionRepository creates a new instance of PositionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionRepository {
	mock := &PositionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
